### ISSUE TITLE
explain tar xzvf error

### ISSUE THREAD

**Issue by shinokada** [jeroenjanssens/dsutils#2]
When I run `explain tar xzvf` I get the following error.
Any idea to solve it?

```
explain tar xzvf
Traceback (most recent call last):
  File "/Users/shinichiokada/.local/share/bin/scrape", line 78, in <module>
    exit(main())
  File "/Users/shinichiokada/.local/share/bin/scrape", line 37, in main
    args.expression = [e.decode('utf-8') for e in args.expression]
  File "/Users/shinichiokada/.local/share/bin/scrape", line 37, in <listcomp>
    args.expression = [e.decode('utf-8') for e in args.expression]
AttributeError: 'str' object has no attribute 'decode'
(23) Failed writing body
```

**Comment by justin-f-perez** [comment]
@shinokada hi!

The line in the traceback...

```python
    args.expression = [e.decode('utf-8') for e in args.expression]
```

... is attempting to convert byte strings, the default string type in python2 ([RIP 2020-01](https://www.python.org/doc/sunset-python-2/)) into a unicode string before reassigning to the same variable. Since python3.0 ([born 2008-12](https://www.python.org/downloads/release/python-300/)), the default string type is unicode string. The solution is to remove this line (and for the author to join us in the 21st century 😜 )

```shell
❯ python

WARNING: Python 2.7 is not recommended.  
This version is included in macOS for compatibility with legacy software.
...
```
```python
>>> type('')
<type 'str'>
>>> type(''.decode('utf-8'))
<type 'unicode'>
>>> exit()
```
```bash
❯ python3
Python 3.9.10 ...
```
```python
>>> type('')
<class 'str'>
>>> type(''.decode('utf-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'
```

Although, this seems to be an oversight. [The book cites python version 3.8](https://datascienceatthecommandline.com/2e/list-of-command-line-tools.html?q=python%20#python-1)
> python
> An interpreted, interactive, object-oriented programming language. python (version 3.8.5) by The Python Software Foundation (2021). More information: https://www.python.org/.
